image: node:16.14.2-bullseye

stages:
  - dependencies
  - build
  - test
  - release
  - deploy

install_dependencies:
  stage: dependencies
  script:
    - npm install
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    changes:
      - "src/"
      - "package.json"
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

test:
  stage: test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm run test -- --no-watch --browsers=ChromeHeadlessCI
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

release:
  stage: release
  script:
    - npx semantic-release
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

deploy:
  stage: deploy
  script:
    - firebase deploy --project portfolio-6725b --token $FIREBASE_TOKEN
  only:
    - main
