image: node:16.14.2-bullseye

stages:
  - dependencies
  - build
  - test
  - release
  - deploy

variables:
  S3_BUCKET_NAME: osfrontahmed
  AWS_REGION: eu-west-3

install_dependencies:
  stage: dependencies
  script:
    - npm install
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

build:
  stage: build
  script:
    - npm run build:ssr
  artifacts:
    paths:
      - dist/
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

test:
  stage: test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm run test -- --no-watch --browsers=ChromeHeadlessCI
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

release:
  stage: release
  script:
    - npx semantic-release
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

# Job Two for deploy build to S3
deploy:
  image: python:latest
  stage: deploy
  before_script:
    - apt-get update -y && apt-get install -y python3-pip
    - pip3 install awscli
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - aws s3 sync dist s3://$S3_BUCKET_NAME
    - eb deploy Osfrontahmed-env
  only: ["main"]
