image: node:16.14.2-bullseye

stages:
  - dependencies
  - build
  - test
  - release
  - artifacts
  - deploy

variables:
  S3_BUCKET_NAME: osfrontahmed
  AWS_REGION: eu-west-3
  ENV_NAME: Osfrontahmed-env
  APP_NAME: osfrontahmed

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build:ssr
  artifacts:
    paths:
      - dist/

test:
  stage: test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm run test -- --no-watch --browsers=ChromeHeadlessCI

release:
  stage: release
  script:
    - npx semantic-release

artifacts:
  stage: artifacts
  dependencies:
    - build
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - cp Procfile dist/
    - zip -r artifact-osFront.zip dist/
  artifacts:
    paths:
      - artifact-osFront.zip

# Job Two for deploy build to S3
deploy:
  stage: deploy
  script:
    - apt-get -q update && apt-get -q -y install zip python3 python3-pip
    - zip -r package.zip . -x "node_modules/*" -x "*.git*"
    - pip3 install awsebcli --upgrade --user
    - export PATH=$PATH:~/.local/bin/
    - eb init $ENV_APP -p node.js -r $AWS_REGION -k $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY
    - eb use $ENV_NAME
    - eb deploy --staged
  only: ["main"]
