image: node:18-alpine

stages:
  - build

variables:
  IMAGE_NAME: docker.io/tebib/osfront:release-$CI_COMMIT_SHORT_SHA

cache:
  key: "${CI_COMMIT_REF_SLUG}-${CACHE_KEY_DEPENDENCIES}"
  paths:
    - node_modules/

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  script:
    # Enable experimental features for Docker CLI
    - echo '{ "experimental": "enabled" }' | sudo tee /etc/docker/daemon.json
    - sudo systemctl restart docker

    # Set up Docker Buildx (only if not already set up)
    - docker buildx version || docker buildx create --use

    # Build and Push the multi-platform image to the registry
    - docker buildx build --platform linux/amd64,linux/arm64 --push -t $IMAGE_NAME .
