stages:
  - build

variables:
  # PACKAGE_VERSION: '$(jq ''.os-front'' < package.json | tr -d ''"'')'
  IMAGE_NAME: docker.io/tebib/osfront:1.10.1
  DOCKER_HOST: tcp://docker:2375
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

default:
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  before_script:
    - docker info

build:
  stage: build
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u $DOCKER_HUB_USERNAME --password-stdin
  script:
    # - docker build -t  $IMAGE_NAME .
    # - docker push  $IMAGE_NAME

    - docker buildx create --use
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx inspect --bootstrap
    - docker buildx build --platform linux/amd64,linux/arm64 --push -t $IMAGE_NAME .
