name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub (optional)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Optional, only needed if pushing

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build multi-arch image
      run: docker buildx build --push --platform linux/amd64,linux/arm64 -t docker.io/tebib/osfront:latest .
